.\" (c) 2012-2019 Michael Pavone
.\" (c) 2019 Carlos Donizete Froes [a.k.a coringao]
.\"
.\" This document is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This package is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this package; if not, see <http://www.gnu.org/licenses/>.
.TH blastem "6" "January 2019" "BlastEm" "The fast and accurate Genesis emulator"
.SH NAME
blastem \- is a highly precise multi-system emulator that emulates the Sega
Genesis/Mega Drive, Master System and Game Gear.
.br
.PP
.SH USAGE
.br
For a list of all command line options:
.PP
\fB\ $ blastem -h\fR
.PP
Extract the tarball/zip to a directory of your choosing.
.br
To run the game from the command line:
.PP
\fB\ $ blastem\fR
.PP
.SH KEYBOARD
.PP
.B Control Genesis/Mega Drive:
.br
---------------------------
.PP
.B 	KEY					ACTION
.br
	===					======
.br
	UP					up arrow
.PP
	DOWN					down arrow
.PP
	LEFT					left arrow
.PP
	RIGHT				right arrow
.PP
	Button A				press letter A
.PP
	Button B				press letter S
.PP
	Button C				press letter D
.PP
	Button X				press letter Q
.PP
	Button Y				press letter W
.PP
	Button Z				press letter E
.PP
	SCREENSHOT			press letter P
.PP
	RESET				press TAB
.PP
	START				press ENTER
.PP
.br
.B Control Game Gear/Master System:
.br
----------------------
.PP
.B 	KEY					ACTION
.br
	===					======
.br
	UP					up arrow
.PP
	DOWN					down arrow
.PP
	LEFT					left arrow
.PP
	RIGHT				right arrow
.PP
	Button A(1)			press letter S
.PP
	Button B(2)			press letter D
.PP
	PAUSE/SELECT			press letter Z
.PP
	SCREENSHOT			press letter P
.PP
	RESET				press TAB
.PP
	START(1)				press letter S
.PP
.SH AUTHOR
BlastEm is developed by Michael Pavone (https://www.retrodev.com/blastem).
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao],
for the Debian project (but may be used by others).
